# Generated by Django 2.1 on 2019-07-16 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staying', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateTimeField(default=datetime.datetime.now)),
                ('checkOut', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('evaluationItems1', models.IntegerField(default=5)),
                ('evaluationItems2', models.IntegerField(default=5)),
                ('evaluationItems3', models.IntegerField(default=5)),
                ('evaluationItems4', models.IntegerField(default=5)),
                ('parentComment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stay.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('checkHours', models.BooleanField(default=False)),
                ('checkDays', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checkInOut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='stay.CheckInOut')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hoursAvailable', models.IntegerField(blank=True, default=0, null=True)),
                ('hoursUntil', models.IntegerField(blank=True, default=0, null=True)),
                ('daysCheckIn', models.IntegerField(default=0)),
                ('daysCheckOut', models.IntegerField(default=0)),
                ('standardPersonnel', models.IntegerField()),
                ('MaximumPersonnel', models.IntegerField()),
                ('hoursPrice', models.CharField(blank=True, max_length=50)),
                ('daysPrice', models.CharField(max_length=50)),
                ('checkHours', models.BooleanField(default=True)),
                ('checkDays', models.BooleanField(default=True)),
                ('saleHoursPrice', models.CharField(blank=True, max_length=50)),
                ('saleDaysPrice', models.CharField(blank=True, max_length=50)),
                ('basicInfo', models.TextField(blank=True)),
                ('reservationNotice', models.TextField()),
                ('cancelRegulation', models.TextField()),
                ('reserved', models.ManyToManyField(blank=True, related_name='reserved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('builtDate', models.DateField(blank=True)),
                ('remodeledDate', models.DateField(blank=True)),
                ('introduce', models.TextField()),
                ('serviceKinds', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '주차가능'), (2, '레스토랑'), (3, '커피숍'), (4, '유료세탁'), (5, '객실금연'), (6, '연회장'), (7, '비즈니스'), (8, '와이파이'), (9, '조식운영'), (10, '스파/월풀'), (11, '수영장'), (12, '파티룸'), (13, '커플PC'), (14, '무인텔'), (15, '바베큐'), (16, '족구장')], max_length=38, null=True)),
                ('serviceIntroduce', models.TextField(blank=True)),
                ('serviceNotice', models.TextField()),
                ('pickupNotice', models.TextField(blank=True)),
                ('directions', models.TextField(blank=True)),
                ('searchTag', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='stays', to='stay.Category')),
                ('like', models.ManyToManyField(blank=True, related_name='like_stay', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='stay.Stay'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='stay.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_room', to='stay.Room'),
        ),
        migrations.AddField(
            model_name='image',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_stay', to='stay.Stay'),
        ),
        migrations.AddField(
            model_name='comment',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stay.Stay'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkinout', to='stay.Room'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkinout', to='stay.Stay'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinout', to=settings.AUTH_USER_MODEL),
        ),
    ]
