# Generated by Django 2.1 on 2019-07-17 22:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0002_auto_20190717_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='room',
        ),
        migrations.RemoveField(
            model_name='checkinout',
            name='stay',
        ),
        migrations.RemoveField(
            model_name='checkinout',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='checkInOut',
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='stay.Stay'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='serviceKinds',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('park', '주차가능'), ('restaurant', '레스토랑'), ('coffeeShop', '커피숍'), ('paidLaundary', '유료세탁'), ('noSmoking', '객실금연'), ('banquetHall', '연회장'), ('business', '비즈니스'), ('wifi', '와이파이'), ('breakfast', '조식운영'), ('spa', '스파/월풀'), ('swimmingPool', '수영장'), ('partyRoom', '파티룸'), ('couplePC', '커플PC'), ('unmanned', '무인텔'), ('barbecue', '바베큐'), ('jokgu', '족구장')], max_length=145, null=True),
        ),
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
