# Generated by Django 2.1 on 2019-07-18 02:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stay', '0003_auto_20190717_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='searchTag',
        ),
        migrations.AddField(
            model_name='stay',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
