# Generated by Django 2.1 on 2019-07-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchKey', models.CharField(max_length=50, unique=True)),
                ('stays', models.ManyToManyField(blank=True, related_name='searchstays', to='stay.Stay')),
            ],
        ),
    ]
